import json

file_path = r'm:\Term 10\Grad\SLR Main\Unified_Dataset_Merger.ipynb'
with open(file_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

for cell in nb['cells']:
    if cell['cell_type'] == 'code' and 'DYNAMIC DATASET EXTRACTION' in ''.join(cell['source']):
        source_code = [
            "# ============================================================\n",
            "# CELL 5 & 6: DYNAMIC DATASET EXTRACTION & VALIDATION (UI OPTIMIZED)\n",
            "# ============================================================\n",
            "\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "from pathlib import Path\n",
            "import ipywidgets as widgets\n",
            "from IPython.display import clear_output, display\n",
            "\n",
            "# ------------------------------------------------------------\n",
            "# 1. VALIDATION FUNCTIONS (Clean Text Output)\n",
            "# ------------------------------------------------------------\n",
            "def extract_and_display_csv(file_path, dataset_name):\n",
            "    if not file_path: return None\n",
            "    path = Path(file_path.strip('\"\\'')) # Strip quotes if pasted\n",
            "    \n",
            "    if not path.exists():\n",
            "        print(f\"  ❌ Error: File not found -> {path}\")\n",
            "        return None\n",
            "        \n",
            "    print(f\"\\n📊 --- {dataset_name} ---\")\n",
            "    df = pd.read_csv(path)\n",
            "    \n",
            "    samples = len(df)\n",
            "    features = len(df.columns) - 1 if 'label' in df.columns else len(df.columns)\n",
            "    \n",
            "    print(f\"  • File:     {path.name}\")\n",
            "    print(f\"  • Samples:  {samples:,}\")\n",
            "    print(f\"  • Features: {features}\")\n",
            "    \n",
            "    if 'label' in df.columns:\n",
            "        num_classes = df['label'].nunique()\n",
            "        print(f\"  • Classes:  {num_classes}\")\n",
            "        \n",
            "        # Check for missing class issue\n",
            "        if num_classes < 29:\n",
            "            print(f\"  ⚠️ WARNING: Found {num_classes} classes instead of 29. Check for missing signs!\")\n",
            "            \n",
            "    # Check for Data Leakage Risk\n",
            "    if 'signer_id' not in df.columns:\n",
            "        print(\"  ⚠️ WARNING: No 'signer_id' column found. Random split may cause data leakage!\")\n",
            "        \n",
            "    return df\n",
            "\n",
            "def extract_and_display_npz(file_path, dataset_name):\n",
            "    if not file_path: return None\n",
            "    path = Path(file_path.strip('\"\\''))\n",
            "    \n",
            "    if not path.exists():\n",
            "        print(f\"  ❌ Error: File not found -> {path}\")\n",
            "        return None\n",
            "        \n",
            "    print(f\"\\n📈 --- {dataset_name} ---\")\n",
            "    data = np.load(path)\n",
            "    X, y = data['X'], data['y']\n",
            "    \n",
            "    print(f\"  • File:      {path.name}\")\n",
            "    print(f\"  • Sequences: {len(X):,}\")\n",
            "    print(f\"  • Shape:     {X.shape} (Sequences, Frames, Features)\")\n",
            "    print(f\"  • Classes:   {len(np.unique(y))}\")\n",
            "    \n",
            "    return X, y\n",
            "\n",
            "# ------------------------------------------------------------\n",
            "# 2. IPYWIDGETS INTERACTIVE DASHBOARD\n",
            "# ------------------------------------------------------------\n",
            "cat_dropdown = widgets.Dropdown(\n",
            "    options=[('Letters (CSV Files)', 'letters'), ('Words (NPZ Files)', 'words')],\n",
            "    value='letters',\n",
            "    description='Category:',\n",
            "    style={'description_width': 'initial'}\n",
            ")\n",
            "\n",
            "# Text inputs for paths instead of tkinter popups\n",
            "path_inputs = [\n",
            "    widgets.Text(placeholder='Paste absolute path to dataset here...', description=f'File {i+1}:', layout=widgets.Layout(width='90%'))\n",
            "    for i in range(4)\n",
            "]\n",
            "\n",
            "btn_extract = widgets.Button(description='🚀 Extract & Validate', button_style='primary', icon='cogs', layout=widgets.Layout(width='auto'))\n",
            "out_logs = widgets.Output()\n",
            "\n",
            "# Global variable to pass to the next cell\n",
            "extracted_data = []\n",
            "\n",
            "def on_extract(b):\n",
            "    with out_logs:\n",
            "        clear_output()\n",
            "        global extracted_data\n",
            "        extracted_data = []\n",
            "        \n",
            "        is_letters = (cat_dropdown.value == 'letters')\n",
            "        paths = [inp.value.strip() for inp in path_inputs if inp.value.strip() != '']\n",
            "        \n",
            "        if not paths:\n",
            "            print(\"❌ ERROR: Please paste at least one file path!\")\n",
            "            return\n",
            "            \n",
            "        print(\"🚀 STARTING DYNAMIC EXTRACTION PIPELINE\")\n",
            "        print(\"=\"*60)\n",
            "        \n",
            "        for i, p in enumerate(paths):\n",
            "            if is_letters:\n",
            "                data = extract_and_display_csv(p, f\"Dataset {i+1}\")\n",
            "            else:\n",
            "                data = extract_and_display_npz(p, f\"Dataset {i+1}\")\n",
            "                \n",
            "            if data is not None:\n",
            "                extracted_data.append(data)\n",
            "                \n",
            "        print(\"\\n\" + \"=\"*60)\n",
            "        print(f\"✅ Extraction Complete. {len(extracted_data)} datasets loaded and ready for the next cell.\")\n",
            "\n",
            "btn_extract.on_click(on_extract)\n",
            "\n",
            "ui = widgets.VBox([\n",
            "    widgets.HTML(\"<h3>📂 Dynamic Dataset Extraction Panel</h3>\"),\n",
            "    widgets.HTML(\"<p><i>Paste the full paths to your files below to avoid UI freezing issues. Leave unused boxes empty.</i></p>\"),\n",
            "    cat_dropdown,\n",
            "    widgets.HTML(\"<br><b>Dataset Paths:</b>\"),\n",
            "    *path_inputs,\n",
            "    widgets.HTML(\"<br>\"),\n",
            "    btn_extract,\n",
            "    out_logs\n",
            "], layout=widgets.Layout(padding='15px', border='2px solid #2196F3', border_radius='10px', background_color='#f0f8ff'))\n",
            "\n",
            "display(ui)\n"
        ]
        cell['source'] = source_code

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
