import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Production Architecture: Real-Time English (ASL) Sign Language Recognition\n",
    "This notebook implements the production-ready pipeline for the SLR system.\n",
    "It features:\n",
    "1. **MediaPipe Holistic**: Extracts full body/face context (prepared for future temporal models).\n",
    "2. **Improved Stabilization**: A robust `commit-once-then-wait` tracker to prevent repetitive letters.\n",
    "3. **ASL MLP Integration**: Hooks up the final English `.h5` model."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import mediapipe as mp\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "import time\n",
    "from collections import deque\n",
    "import os\n",
    "\n",
    "print(\"✓ Libraries imported successfully\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. GPU Configuration\n",
    "Ensure TensorFlow doesn't crash by managing GPU memory growth."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "gpus = tf.config.list_physical_devices('GPU')\n",
    "if gpus:\n",
    "    try:\n",
    "        for gpu in gpus:\n",
    "            tf.config.experimental.set_memory_growth(gpu, True)\n",
    "        print(f\"✓ GPU configured: {len(gpus)} GPU(s) available\")\n",
    "    except RuntimeError as e:\n",
    "        print(f\"⚠️ GPU config error: {e}\")\n",
    "else:\n",
    "    print(\"ℹ️ No GPU detected, using CPU\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Configuration & Parameters\n",
    "Set paths, thresholds, and class labels."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Model Path (English Final Model)\n",
    "MODEL_PATH = r\"asl_mediapipe_mlp_model.h5\"\n",
    "\n",
    "# Stabilization Settings\n",
    "STABILIZATION_WINDOW_SIZE = 15  # Buffer size for majority vote\n",
    "STABILIZATION_THRESHOLD = 11    # Minimum matches in buffer (11/15 = ~73% majority)\n",
    "MIN_CONFIDENCE = 0.75           # Minimum confidence to consider a prediction\n",
    "HOLD_COOLDOWN_SECONDS = 1.2     # Soft-lock time after committing a letter\n",
    "\n",
    "# Display Settings\n",
    "DISPLAY_WIDTH = 1280\n",
    "DISPLAY_HEIGHT = 720\n",
    "\n",
    "# English ASL Class Labels (26 Letters + 3 Controls)\n",
    "CLASS_LABELS = [\n",
    "    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',\n",
    "    'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',\n",
    "    'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',\n",
    "    'Y', 'Z', 'del', 'nothing', 'space'\n",
    "]\n",
    "print(\"✓ Settings configured\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Preprocessing (MediaPipe Holistic)\n",
    "Extracting hand landmarks. Using Holistic prepares the pipeline for future GRU models that require face/pose data."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "mp_holistic = mp.solutions.holistic\n",
    "mp_drawing = mp.solutions.drawing_utils\n",
    "mp_drawing_styles = mp.solutions.drawing_styles\n",
    "\n",
    "holistic = mp_holistic.Holistic(\n",
    "    static_image_mode=False,\n",
    "    min_detection_confidence=0.5,\n",
    "    min_tracking_confidence=0.5\n",
    ")\n",
    "\n",
    "def extract_features(results):\n",
    "    \"\"\"\n",
    "    Extracts hand features compatible with the current MLP model.\n",
    "    Returns a flattened array of 63 features, or None if no hand detected.\n",
    "    \"\"\"\n",
    "    # Prioritize right hand, then left hand\n",
    "    if results.right_hand_landmarks:\n",
    "        landmarks = results.right_hand_landmarks.landmark\n",
    "    elif results.left_hand_landmarks:\n",
    "        landmarks = results.left_hand_landmarks.landmark\n",
    "    else:\n",
    "        return None\n",
    "\n",
    "    # Extract 21 points * 3 coordinates = 63 features\n",
    "    features = np.array([[lm.x, lm.y, lm.z] for lm in landmarks]).flatten()\n",
    "    return features.reshape(1, -1)\n",
    "\n",
    "print(\"✓ Preprocessing functions defined\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Stabilization Tracker\n",
    "This class manages the rolling buffer and enforces the `commit-once-then-wait` logic."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class StabilizationTracker:\n",
    "    def __init__(self):\n",
    "        self.buffer = deque(maxlen=STABILIZATION_WINDOW_SIZE)\n",
    "        self.committed_label = None\n",
    "        self.cooldown_until = 0\n",
    "\n",
    "    def update(self, label, confidence):\n",
    "        now = time.time()\n",
    "        \n",
    "        # If no hand/sign detected, clear buffer and release lock\n",
    "        if label is None or label == 'nothing':\n",
    "            self.buffer.clear()\n",
    "            self.committed_label = None\n",
    "            return None, 0.0, \"waiting\", 0\n",
    "\n",
    "        # If in cooldown for this specific label, ignore it\n",
    "        if self.committed_label == label and now < self.cooldown_until:\n",
    "            return label, confidence, \"cooldown\", 100\n",
    "\n",
    "        # Add to buffer\n",
    "        self.buffer.append(label)\n",
    "        \n",
    "        # Calculate majority\n",
    "        count = self.buffer.count(label)\n",
    "        progress = (count / STABILIZATION_THRESHOLD) * 100\n",
    "        \n",
    "        if count >= STABILIZATION_THRESHOLD and len(self.buffer) == STABILIZATION_WINDOW_SIZE:\n",
    "            # Commit the label\n",
    "            self.committed_label = label\n",
    "            self.cooldown_until = now + HOLD_COOLDOWN_SECONDS\n",
    "            self.buffer.clear()\n",
    "            return label, confidence, \"committed\", 100\n",
    "            \n",
    "        return label, confidence, \"stabilizing\", min(100, int(progress))\n",
    "\n",
    "print(\"✓ Tracker class defined\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 5. Load Model\n",
    "Loads the trained ASL MLP model."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "try:\n",
    "    if os.path.exists(MODEL_PATH):\n",
    "        model = tf.keras.models.load_model(MODEL_PATH)\n",
    "        print(\"✓ ASL MLP Model loaded successfully\")\n",
    "    else:\n",
    "        print(f\"❌ Error: Model not found at {MODEL_PATH}\")\n",
    "        print(\"Please check the path and run this cell again.\")\n",
    "        model = None\n",
    "except Exception as e:\n",
    "    print(f\"❌ Error loading model: {e}\")\n",
    "    model = None"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 6. Main Recognition Loop\n",
    "Run this cell to open the webcam and start recognizing signs."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def run_sign_recognition():\n",
    "    if model is None:\n",
    "        print(\"❌ Model not loaded. Cannot run recognition.\")\n",
    "        return\n",
    "        \n",
    "    cap = cv2.VideoCapture(0)\n",
    "    if not cap.isOpened():\n",
    "        print(\"❌ Cannot access camera\")\n",
    "        return\n",
    "        \n",
    "    print(\"\\n==================================================\")\n",
    "    print(\"🤟 ASL SIGN LANGUAGE RECOGNITION STARTED\")\n",
    "    print(\"==================================================\")\n",
    "    print(\"Controls:\")\n",
    "    print(\"  'q' - Quit\")\n",
    "    print(\"  'c' - Clear sentence\")\n",
    "    print(\"==================================================\\n\")\n",
    "    \n",
    "    window_name = \"ASL SLR - Production Architecture\"\n",
    "    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)\n",
    "    cv2.resizeWindow(window_name, DISPLAY_WIDTH, DISPLAY_HEIGHT)\n",
    "    \n",
    "    tracker = StabilizationTracker()\n",
    "    predicted_sentence = \"\"\n",
    "    \n",
    "    fps_start_time = time.time()\n",
    "    frame_count = 0\n",
    "    fps_display = 0\n",
    "    \n",
    "    try:\n",
    "        while True:\n",
    "            ret, frame = cap.read()\n",
    "            if not ret:\n",
    "                break\n",
    "                \n",
    "            frame = cv2.resize(frame, (DISPLAY_WIDTH, DISPLAY_HEIGHT))\n",
    "            \n",
    "            # MediaPipe requires RGB\n",
    "            rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)\n",
    "            rgb_frame.flags.writeable = False\n",
    "            results = holistic.process(rgb_frame)\n",
    "            rgb_frame.flags.writeable = True\n",
    "            \n",
    "            # Default UI state\n",
    "            display_status = \"No hand detected\"\n",
    "            status_color = (150, 150, 150)\n",
    "            \n",
    "            # Draw Holistic landmarks\n",
    "            if results.face_landmarks:\n",
    "                mp_drawing.draw_landmarks(frame, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION,\n",
    "                                        mp_drawing_styles.get_default_face_mesh_tesselation_style())\n",
    "            if results.pose_landmarks:\n",
    "                mp_drawing.draw_landmarks(frame, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,\n",
    "                                        mp_drawing_styles.get_default_pose_landmarks_style())\n",
    "            if results.right_hand_landmarks:\n",
    "                mp_drawing.draw_landmarks(frame, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS)\n",
    "            if results.left_hand_landmarks:\n",
    "                mp_drawing.draw_landmarks(frame, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS)\n",
    "            \n",
    "            # Extract features and Predict\n",
    "            features = extract_features(results)\n",
    "            if features is not None:\n",
    "                # Inference\n",
    "                input_tensor = tf.cast(features, tf.float32)\n",
    "                prediction = model.predict(input_tensor, verbose=0)[0]\n",
    "                \n",
    "                class_idx = np.argmax(prediction)\n",
    "                conf = float(prediction[class_idx])\n",
    "                raw_label = CLASS_LABELS[class_idx]\n",
    "                \n",
    "                if conf < MIN_CONFIDENCE:\n",
    "                    raw_label = None\n",
    "                    display_status = f\"Low confidence: {conf:.0%}\"\n",
    "                    status_color = (0, 100, 255)\n",
    "                    tracker.update(None, 0.0) # Reset tracker\n",
    "                else:\n",
    "                    # Stabilize\n",
    "                    tracked_label, tracked_conf, status, progress = tracker.update(raw_label, conf)\n",
    "                    \n",
    "                    if status == \"stabilizing\":\n",
    "                        display_status = f\"{tracked_label} ({tracked_conf:.0%}) Stabilizing {progress}%\"\n",
    "                        status_color = (0, 255, 255)\n",
    "                    elif status == \"cooldown\":\n",
    "                        display_status = f\"{tracked_label} ({tracked_conf:.0%}) ✓ Committed - change sign\"\n",
    "                        status_color = (255, 200, 0)\n",
    "                    elif status == \"committed\":\n",
    "                        display_status = f\"{tracked_label} ({tracked_conf:.0%}) ✓ COMMITTED!\"\n",
    "                        status_color = (0, 255, 0)\n",
    "                        \n",
    "                        # Sentence building\n",
    "                        if tracked_label == \"space\":\n",
    "                            if not predicted_sentence.endswith(\" \"):\n",
    "                                predicted_sentence += \" \"\n",
    "                        elif tracked_label == \"del\":\n",
    "                            if predicted_sentence:\n",
    "                                predicted_sentence = predicted_sentence[:-1]\n",
    "                        elif tracked_label != \"nothing\":\n",
    "                            predicted_sentence += tracked_label\n",
    "            else:\n",
    "                tracker.update(None, 0.0)\n",
    "                \n",
    "            # Mirror the frame\n",
    "            frame = cv2.flip(frame, 1)\n",
    "            \n",
    "            # Calculate FPS\n",
    "            frame_count += 1\n",
    "            if time.time() - fps_start_time >= 1.0:\n",
    "                fps_display = frame_count\n",
    "                frame_count = 0\n",
    "                fps_start_time = time.time()\n",
    "                \n",
    "            # Draw UI\n",
    "            cv2.rectangle(frame, (0, 0), (DISPLAY_WIDTH, 70), (30, 30, 30), -1)\n",
    "            cv2.putText(frame, f\"FPS: {fps_display} | 'q'=quit 'c'=clear\", (10, 25), \n",
    "                       cv2.FONT_HERSHEY_SIMPLEX, 0.6, (200, 200, 200), 1)\n",
    "            \n",
    "            # Draw status (Standard English, no need for PIL reshaper)\n",
    "            cv2.putText(frame, display_status, (10, 55), cv2.FONT_HERSHEY_SIMPLEX, 1, status_color, 2)\n",
    "            \n",
    "            # Draw sentence bar\n",
    "            bar_height = 80\n",
    "            cv2.rectangle(frame, (0, DISPLAY_HEIGHT - bar_height), \n",
    "                         (DISPLAY_WIDTH, DISPLAY_HEIGHT), (30, 30, 30), -1)\n",
    "            \n",
    "            cv2.putText(frame, predicted_sentence[-40:], (20, DISPLAY_HEIGHT - 30), \n",
    "                        cv2.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 2)\n",
    "            \n",
    "            cv2.imshow(window_name, frame)\n",
    "            \n",
    "            key = cv2.waitKey(1) & 0xFF\n",
    "            if key == ord('q'):\n",
    "                break\n",
    "            elif key == ord('c'):\n",
    "                predicted_sentence = \"\"\n",
    "                tracker.update(None, 0.0)\n",
    "                print(\"🗑️ Sentence cleared\")\n",
    "                \n",
    "    finally:\n",
    "        cap.release()\n",
    "        cv2.destroyAllWindows()\n",
    "        print(f\"\\n📝 Final sentence: {predicted_sentence}\")\n",
    "\n",
    "# Run it!\n",
    "run_sign_recognition()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

with open(r'c:\Users\HADEEL GAMALELDIN\Downloads\Letters_ORIGINAL\Base_Pipeline_English_Letters\Production_Architecture_English.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)
