"""
Patch ArSL_Word_Live_Test.ipynb - Fix Top 3 BiDi flipping + alignment issues:
  - Rank numbers and percentages rendered with cv2.putText (no BiDi distortion)
  - Arabic words rendered with PIL (correct RTL shaping)
  - Fixed x-column positions so nothing overlaps
"""
import json
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")

NB_PATH = Path(__file__).parent / "ArSL_Word_Live_Test.ipynb"

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

cells = nb["cells"]

CELL5_NEW_SOURCE = [
    "# ===============================\n",
    "# CELL 5: LIVE WEBCAM TESTING\n",
    "# ===============================\n",
    "\n",
    "FONT = cv2.FONT_HERSHEY_SIMPLEX\n",
    "\n",
    "def run_live_test():\n",
    "    cap = cv2.VideoCapture(CAMERA_INDEX)\n",
    "    cap.set(cv2.CAP_PROP_FRAME_WIDTH, CAMERA_WIDTH)\n",
    "    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, CAMERA_HEIGHT)\n",
    "    cap.set(cv2.CAP_PROP_BUFFERSIZE, 1)\n",
    "    cap.set(cv2.CAP_PROP_FPS, 30)\n",
    "\n",
    "    if not cap.isOpened():\n",
    "        print('Cannot open camera!'); return\n",
    "\n",
    "    print(f'Camera opened [{NUM_HANDS}H/{NUM_FEATURES}F].')\n",
    "    print('(Q) Quit  (R/C) Clear  (SPACE) Space  (D/BACKSPACE) Delete')\n",
    "\n",
    "    frame_buffer       = deque(maxlen=SEQUENCE_LENGTH)\n",
    "    prediction_history = deque(maxlen=STABILITY_WINDOW)\n",
    "    sentence_words_en  = []\n",
    "    sentence_words_ar  = []\n",
    "    current_word_en    = ''\n",
    "    current_word_ar    = ''\n",
    "    current_conf       = 0.0\n",
    "    last_pred_time     = 0.0\n",
    "    last_conf_time     = 0.0\n",
    "    last_erase_time    = 0.0\n",
    "    hand_detected      = False\n",
    "    hands_count        = 0\n",
    "    fps_history        = deque(maxlen=30)\n",
    "    top3               = []\n",
    "\n",
    "    # ── Colors (BGR) ──\n",
    "    GREEN  = (0, 200, 0)\n",
    "    RED    = (0, 0, 200)\n",
    "    WHITE  = (255, 255, 255)\n",
    "    BLACK  = (0, 0, 0)\n",
    "    YELLOW = (0, 210, 210)\n",
    "    ORANGE = (0, 140, 255)\n",
    "    GRAY   = (70, 70, 70)\n",
    "    LGRAY  = (160, 160, 160)\n",
    "\n",
    "    # ── Layout constants (absolute, for 1280x720 display) ──\n",
    "    TOP_H   = 115   # top bar height\n",
    "    BOT_H   = 82    # bottom bar height\n",
    "    # Zone x boundaries inside top bar:\n",
    "    #   LEFT   0  ..  470  : Word + Confidence %\n",
    "    #   CENTER 485 ..  700  : Progress bars\n",
    "    #   RIGHT  715 .. 1280  : Top-3 predictions\n",
    "    L_END  = 470\n",
    "    C_X    = 485\n",
    "    C_END  = 700\n",
    "    R_X    = 715\n",
    "\n",
    "    while True:\n",
    "        t0 = time.time()\n",
    "        ret, frame = cap.read()\n",
    "        if not ret: break\n",
    "\n",
    "        frame = cv2.flip(frame, 1)\n",
    "        # Upscale BEFORE drawing so UI is crisp at display resolution\n",
    "        frame = cv2.resize(frame, (DISPLAY_WIDTH, DISPLAY_HEIGHT))\n",
    "        h, w = frame.shape[:2]   # 720, 1280\n",
    "        now  = time.time()\n",
    "\n",
    "        # ── Landmark extraction ──────────────────────────────────────────────\n",
    "        landmarks, draw_items = extract_landmarks(frame)\n",
    "        hands_count  = sum(1 for t, _ in draw_items if t == 'hand')\n",
    "        hand_detected = hands_count > 0\n",
    "        frame_buffer.append(landmarks)\n",
    "\n",
    "        # ── Erase gesture ────────────────────────────────────────────────────\n",
    "        if NUM_FEATURES == 258 and (now - last_erase_time) > 2.0:\n",
    "            ls_x, ls_y = landmarks[44], landmarks[45]\n",
    "            rs_x, rs_y = landmarks[48], landmarks[49]\n",
    "            lw_x, lw_y = landmarks[60], landmarks[61]\n",
    "            rw_x, rw_y = landmarks[64], landmarks[65]\n",
    "            if ls_x and rs_x and lw_x and rw_x:\n",
    "                d1 = ((lw_x-rs_x)**2 + (lw_y-rs_y)**2)**0.5\n",
    "                d2 = ((rw_x-ls_x)**2 + (rw_y-ls_y)**2)**0.5\n",
    "                if d1 < 0.2 and d2 < 0.2 and sentence_words_en:\n",
    "                    sentence_words_en.pop()\n",
    "                    if sentence_words_ar: sentence_words_ar.pop()\n",
    "                    cv2.putText(frame, 'WORD ERASED!', (w//2-180, h//2),\n",
    "                                FONT, 2.0, RED, 4)\n",
    "                    print('Erase gesture: deleted last word.')\n",
    "                    last_erase_time = now\n",
    "                    frame_buffer.clear()\n",
    "\n",
    "        # ── Draw landmarks ───────────────────────────────────────────────────\n",
    "        for item_type, lm in draw_items:\n",
    "            if item_type == 'hand':\n",
    "                mp_drawing.draw_landmarks(frame, lm, mp_hands.HAND_CONNECTIONS,\n",
    "                    mp_drawing_styles.get_default_hand_landmarks_style(),\n",
    "                    mp_drawing_styles.get_default_hand_connections_style())\n",
    "            elif item_type == 'pose':\n",
    "                mp_drawing.draw_landmarks(frame, lm, mp_holistic.POSE_CONNECTIONS,\n",
    "                    mp_drawing_styles.get_default_pose_landmarks_style())\n",
    "\n",
    "        # ── Prediction ───────────────────────────────────────────────────────\n",
    "        if len(frame_buffer) == SEQUENCE_LENGTH and (now - last_pred_time) >= PREDICTION_INTERVAL:\n",
    "            last_pred_time = now\n",
    "            seq = np.array(list(frame_buffer), dtype=np.float32)\n",
    "            seq = (seq - scaler_mean) / scaler_scale\n",
    "            seq = np.expand_dims(seq, 0)\n",
    "            nz  = np.sum(np.any(seq[0] != 0, axis=1))\n",
    "            if nz >= SEQUENCE_LENGTH * 0.3:\n",
    "                proba    = model(seq, training=False).numpy()[0]\n",
    "                pred_idx = int(np.argmax(proba))\n",
    "                pred_conf = float(proba[pred_idx])\n",
    "                pred_en  = index_to_english.get(pred_idx, '?')\n",
    "                pred_ar  = index_to_arabic.get(pred_idx, '?')\n",
    "                top3_idx = np.argsort(proba)[-3:][::-1]\n",
    "                top3 = [(index_to_english.get(i,'?'), index_to_arabic.get(i,'?'), float(proba[i]))\n",
    "                        for i in top3_idx]\n",
    "                if pred_conf >= CONFIDENCE_THRESHOLD:\n",
    "                    current_word_en = pred_en\n",
    "                    current_word_ar = pred_ar\n",
    "                    current_conf    = pred_conf\n",
    "                    prediction_history.append(pred_en)\n",
    "                    if (len(prediction_history) == STABILITY_WINDOW and\n",
    "                        len(set(prediction_history)) == 1 and\n",
    "                        (now - last_conf_time) >= COOLDOWN_TIME):\n",
    "                        sentence_words_en.append(current_word_en)\n",
    "                        sentence_words_ar.append(current_word_ar)\n",
    "                        last_conf_time = now\n",
    "                        prediction_history.clear()\n",
    "                        print(f'Confirmed: \"{current_word_ar}\" ({current_conf:.1%})')\n",
    "                else:\n",
    "                    current_word_en = current_word_ar = ''\n",
    "                    current_conf = 0.0\n",
    "            else:\n",
    "                current_word_en = current_word_ar = ''\n",
    "                current_conf = 0.0\n",
    "\n",
    "        # ════════════════════════════════════════════════════════════════\n",
    "        #  TOP HUD  (three non-overlapping zones)\n",
    "        # ════════════════════════════════════════════════════════════════\n",
    "        cv2.rectangle(frame, (0,0), (w, TOP_H), BLACK, -1)\n",
    "        cv2.rectangle(frame, (0,0), (w, TOP_H), WHITE, 2)\n",
    "        cv2.line(frame, (L_END+7, 10), (L_END+7, TOP_H-10), GRAY, 1)\n",
    "        cv2.line(frame, (C_END+7, 10), (C_END+7, TOP_H-10), GRAY, 1)\n",
    "\n",
    "        if current_word_en:\n",
    "            clr = GREEN if current_conf >= 0.6 else YELLOW if current_conf >= 0.4 else ORANGE\n",
    "\n",
    "            # ── LEFT: 'Word:' label (cv2) + Arabic word (PIL) on same line ──\n",
    "            cv2.putText(frame, 'Word:', (14, 43), FONT, 1.05, clr, 2)\n",
    "            word_label = current_word_ar if current_word_ar else current_word_en\n",
    "            frame = draw_arabic_text(frame, word_label, (130, 6), font_size=36, color=clr)\n",
    "\n",
    "            # 'Confidence:' label (cv2) + value (cv2) on second line\n",
    "            cv2.putText(frame, f'Confidence: {current_conf:.1%}', (14, 85), FONT, 0.75, clr, 2)\n",
    "\n",
    "            # ── CENTER: confidence bar + stability bar ───────────────────────\n",
    "            BAR_W = C_END - C_X - 8\n",
    "\n",
    "            # Confidence bar\n",
    "            cv2.putText(frame, 'Conf', (C_X, 18), FONT, 0.46, LGRAY, 1)\n",
    "            BY1 = 22; BH1 = 24\n",
    "            cv2.rectangle(frame, (C_X, BY1), (C_X+BAR_W, BY1+BH1), GRAY, -1)\n",
    "            cv2.rectangle(frame, (C_X, BY1), (C_X+int(BAR_W*current_conf), BY1+BH1), clr, -1)\n",
    "            cv2.rectangle(frame, (C_X, BY1), (C_X+BAR_W, BY1+BH1), WHITE, 1)\n",
    "\n",
    "            # Stability bar\n",
    "            stable = sum(1 for p in prediction_history if p == current_word_en)\n",
    "            BY2 = BY1 + BH1 + 22\n",
    "            cv2.putText(frame, f'Stability  {stable}/{STABILITY_WINDOW}',\n",
    "                        (C_X, BY2 - 4), FONT, 0.46, LGRAY, 1)\n",
    "            BH2 = 16\n",
    "            cv2.rectangle(frame, (C_X, BY2), (C_X+BAR_W, BY2+BH2), GRAY, -1)\n",
    "            cv2.rectangle(frame, (C_X, BY2),\n",
    "                          (C_X+int(BAR_W*stable/max(STABILITY_WINDOW,1)), BY2+BH2), WHITE, -1)\n",
    "            cv2.rectangle(frame, (C_X, BY2), (C_X+BAR_W, BY2+BH2), WHITE, 1)\n",
    "\n",
    "            # ── RIGHT: Top-3  (rank=cv2 | Arabic=PIL | pct=cv2) ─────────────\n",
    "            # Separate rendering avoids BiDi flipping rank numbers and percentages\n",
    "            cv2.putText(frame, 'Top 3:', (R_X, 16), FONT, 0.50, LGRAY, 1)\n",
    "            PCT_X = w - 8   # right-align percentages here\n",
    "            for rank, (tw_en, tw_ar, tc) in enumerate(top3):\n",
    "                label    = tw_ar if tw_ar else tw_en\n",
    "                y_pil    = 20 + rank * 32          # PIL: top-left of text\n",
    "                y_cv     = y_pil + 22              # cv2: baseline\n",
    "                rank_clr = WHITE if rank == 0 else LGRAY\n",
    "                pct_str  = f'{tc:.1%}'\n",
    "\n",
    "                # Rank number at left of right zone\n",
    "                cv2.putText(frame, f'{rank+1}.', (R_X, y_cv), FONT, 0.55, rank_clr, 1)\n",
    "\n",
    "                # Percentage at fixed right column (right-aligned)\n",
    "                (ptw, _), _ = cv2.getTextSize(pct_str, FONT, 0.52, 1)\n",
    "                cv2.putText(frame, pct_str, (PCT_X - ptw, y_cv), FONT, 0.52, LGRAY, 1)\n",
    "\n",
    "                # Arabic word in the space between rank and percentage\n",
    "                arabic_x   = R_X + 32\n",
    "                arabic_end = PCT_X - ptw - 12\n",
    "                frame = draw_arabic_text(frame, label, (arabic_x, y_pil),\n",
    "                                         font_size=20, color=rank_clr)\n",
    "        else:\n",
    "            status = 'Show a sign...' if hand_detected else 'No hand detected'\n",
    "            cv2.putText(frame, status, (15, 62), FONT, 1.1, LGRAY, 2)\n",
    "\n",
    "        # ════════════════════════════════════════════════════════════════\n",
    "        #  BOTTOM SENTENCE BAR\n",
    "        # ════════════════════════════════════════════════════════════════\n",
    "        cv2.rectangle(frame, (0, h-BOT_H), (w, h), BLACK, -1)\n",
    "        cv2.rectangle(frame, (0, h-BOT_H), (w, h), WHITE, 2)\n",
    "\n",
    "        sent_ar = ' '.join(sentence_words_ar) if sentence_words_ar else '(sentence will appear here)'\n",
    "        sent_en = ' '.join(sentence_words_en) if sentence_words_en else ''\n",
    "\n",
    "        # 'AR:' label (cv2) stays LTR; Arabic sentence (PIL) appears after it\n",
    "        cv2.putText(frame, 'AR:', (12, h-BOT_H+34), FONT, 0.78, (80,220,80), 2)\n",
    "        frame = draw_arabic_text(frame, sent_ar, (68, h-BOT_H+6), font_size=26, color=(80,220,80))\n",
    "\n",
    "        cv2.putText(frame, 'EN:', (12, h-BOT_H+68), FONT, 0.70, WHITE, 1)\n",
    "        frame = draw_arabic_text(frame, sent_en, (68, h-BOT_H+44), font_size=22, color=WHITE)\n",
    "\n",
    "        # ════════════════════════════════════════════════════════════════\n",
    "        #  OVERLAYS on video area\n",
    "        # ════════════════════════════════════════════════════════════════\n",
    "        # Buffer (bottom-left above bar)\n",
    "        buf_clr = GREEN if len(frame_buffer) >= SEQUENCE_LENGTH else YELLOW\n",
    "        cv2.putText(frame, f'Buffer: {len(frame_buffer)}/{SEQUENCE_LENGTH}',\n",
    "                    (12, h-BOT_H-12), FONT, 0.55, buf_clr, 1)\n",
    "\n",
    "        # Hand status (bottom-right above bar)\n",
    "        if NUM_HANDS == 2:\n",
    "            h_clr  = GREEN if hands_count==2 else YELLOW if hands_count==1 else RED\n",
    "            h_txt  = f'HANDS: {hands_count}/2' if hands_count else 'NO HANDS'\n",
    "        else:\n",
    "            h_clr  = GREEN if hand_detected else RED\n",
    "            h_txt  = 'HAND OK' if hand_detected else 'NO HAND'\n",
    "        (htw, _), _ = cv2.getTextSize(h_txt, FONT, 0.55, 1)\n",
    "        cv2.putText(frame, h_txt, (w-htw-24, h-BOT_H-12), FONT, 0.55, h_clr, 1)\n",
    "        cv2.circle(frame, (w-12, h-BOT_H-18), 7, h_clr, -1)\n",
    "\n",
    "        # FPS + mode (top-right below top bar)\n",
    "        fps = 1.0 / max(time.time()-t0, 1e-6)\n",
    "        fps_history.append(fps)\n",
    "        avg_fps = sum(fps_history)/len(fps_history)\n",
    "        cv2.putText(frame, f'FPS: {avg_fps:.0f}', (w-105, TOP_H+22), FONT, 0.60, WHITE, 1)\n",
    "        cv2.putText(frame, f'ArSL | {NUM_HANDS}H/{NUM_FEATURES}F',\n",
    "                    (w-195, TOP_H+42), FONT, 0.48, LGRAY, 1)\n",
    "\n",
    "        cv2.imshow('ArSL Word Recognition - Live Test', frame)\n",
    "\n",
    "        key = cv2.waitKey(1) & 0xFF\n",
    "        if key == ord('q'):\n",
    "            break\n",
    "        elif key in (ord('r'), ord('c')):\n",
    "            sentence_words_en.clear(); sentence_words_ar.clear()\n",
    "            prediction_history.clear()\n",
    "            current_word_en = current_word_ar = ''\n",
    "            print('Cleared.')\n",
    "        elif key == 32:\n",
    "            sentence_words_en.append(' '); sentence_words_ar.append(' ')\n",
    "        elif key in (8, 127) or key == ord('d') or key == ord('x'):\n",
    "            if sentence_words_en:\n",
    "                re = sentence_words_en.pop()\n",
    "                ra = sentence_words_ar.pop() if sentence_words_ar else ''\n",
    "                print(f'Removed: \"{re}\" / \"{ra}\"')\n",
    "\n",
    "    cap.release()\n",
    "    cv2.destroyAllWindows()\n",
    "    fe = ' '.join(sentence_words_en)\n",
    "    fa = ' '.join(sentence_words_ar)\n",
    "    print(f'\\nFinal (EN): {fe}')\n",
    "    print(f'Final (AR): {fa}')\n",
    "    return fe, fa\n",
    "\n",
    "result = run_live_test()\n",
]

def source_to_str(src): return "".join(src)

patched = 0
for cell in nb["cells"]:
    if cell.get("cell_type") != "code": continue
    src = source_to_str(cell["source"])
    if "def run_live_test():" in src and "cv2.VideoCapture" in src:
        cell["source"] = CELL5_NEW_SOURCE
        cell["outputs"] = []
        cell["execution_count"] = None
        print("✅ Patched Cell 5 (alignment fix)")
        patched += 1

print(f"\nTotal: {patched}")
with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print(f"✅ Saved: {NB_PATH}")
